# Generated by Django 4.2.7 on 2023-11-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordresetCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
