# Generated by Django 4.2.7 on 2023-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='qyIUCYGz7al41ugQzp7PS7NLEQnjR5', max_length=30),
        ),
    ]
